---
version: '2'

catalog:
  name: OpenSSH
  version: 0.0.6
  description: An OpenSSH server in a container
  questions:
    - variable: SSH_PORT
      label: SSH port on container
      description: The TCP port to listen on
      type: int
      default: 2222
      required: true
    - variable: LOADBALANCER_PORT
      label: SSH port on loadbalancer
      description: The TCP port to listen on
      type: int
      default: 2222
      required: true

services:
  lb:
    scale: 2
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
        - path: ''
          priority: 1
          protocol: tcp
          service: openssh
          source_port: ${LOADBALANCER_PORT}
          target_port: ${SSH_PORT}
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000

  openssh:
    scale: 2
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 22
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
