---
name: AWX 13
description: AWX provides a web-based user interface, REST API, and task engine built on top of Ansible.
version: 1.0.0
category: Platform
maintainer: Robert de Bock <robert@meinit.nl>
license: Apache-2.0
projectURL: "https://robertdebock.nl/"
