version: '2'
catalog:
  name: AWX
  version: 0.0.3
  description: AWX provides a web-based user interface, REST API, and task engine built on top of [Ansible](https://github.com/ansible/ansible).
  questions:
    - variable: AWX_SECRET_KEY
      label: Secret key
      description: A secret key that's used to encrypt sensitive data
      type: string
      default: a1b2c3d4e5f6
      required: true
    - variable: LB_LISTEN_PORT
      label: Load Balancer Listen Port
      description: Specify a port for the Load Balancer to listen on
      type: int
      default: 8053
      required: true
    - variable: POSTGRES_USER
      label: PostgreSQL username
      description: The username for the PostgreSQL database
      type: string
      default: awx
      required: true
    - variable: POSTGRES_PASSWORD
      label: PostgreSQL password
      description: The password for the PostgreSQL database
      type: string
      default: awxpass
      required: true
    - variable: POSTGRES_DB
      label: PostgreSQL database name
      description: The database name for the PostgreSQL database
      type: string
      default: awx
      required: true

services:
  lb:
    scale: 2
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
        - path: ''
          priority: 1
          protocol: http
          service: web
          source_port: ${LB_LISTEN_PORT}
          target_port: 8052
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  web:
    scale: 2
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
